# Generated by Django 4.2.19 on 2025-03-03 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_subscriptionplan_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission'),
        ),
    ]
