# Generated by Django 4.2.19 on 2025-03-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
