# Generated by Django 4.2.19 on 2025-03-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
